Make 'css_path' a string for Nuitka
Nuitka is complaining that:
> TypeError: can only concatenate str (not "PosixPath") to str

So it wants it to be a string...